apiVersion: v2
name: evolution-todo
description: Evolution of Todo â€” Phase III chatbot (Phase IV K8s deployment)
type: application
version: 0.4.0
appVersion: "0.4.0"
keywords:
  - todo
  - hackathon
  - fastapi
  - nextjs
